/// Flutter icons FlutterIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  FlutterIcons
///      fonts:
///       - asset: fonts/FlutterIcons.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
///
import 'package:flutter/widgets.dart';

class FlutterIcons {
  FlutterIcons._();

  static const _kFontFam = 'FlutterIcons';

  static const IconData home = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData pencil = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData sun = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData moon = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData lock = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData cog = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData heart = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData star = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData flag = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData envelope = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData paperclip = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData eye = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData file_add = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData enter = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData exit = const IconData(0xe820, fontFamily: _kFontFam);
  static const IconData camera = const IconData(0xe826, fontFamily: _kFontFam);
  static const IconData picture = const IconData(0xe827, fontFamily: _kFontFam);
  static const IconData bookmark = const IconData(0xe829, fontFamily: _kFontFam);
  static const IconData user = const IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData location = const IconData(0xe835, fontFamily: _kFontFam);
  static const IconData calendar_full = const IconData(0xe836, fontFamily: _kFontFam);
  static const IconData lnr_bubble = const IconData(0xe83f, fontFamily: _kFontFam);
  static const IconData smile = const IconData(0xe854, fontFamily: _kFontFam);
  static const IconData sad = const IconData(0xe855, fontFamily: _kFontFam);
  static const IconData neutral = const IconData(0xe856, fontFamily: _kFontFam);
  static const IconData alarm = const IconData(0xe858, fontFamily: _kFontFam);
  static const IconData mic = const IconData(0xe85e, fontFamily: _kFontFam);
  static const IconData bug = const IconData(0xe869, fontFamily: _kFontFam);
  static const IconData thumbs_up = const IconData(0xe86d, fontFamily: _kFontFam);
  static const IconData thumbs_down = const IconData(0xe86e, fontFamily: _kFontFam);
  static const IconData magnifier = const IconData(0xe86f, fontFamily: _kFontFam);
  static const IconData cross = const IconData(0xe870, fontFamily: _kFontFam);
  static const IconData menu = const IconData(0xe871, fontFamily: _kFontFam);
  static const IconData chevron_up = const IconData(0xe873, fontFamily: _kFontFam);
  static const IconData chevron_down = const IconData(0xe874, fontFamily: _kFontFam);
  static const IconData chevron_left = const IconData(0xe875, fontFamily: _kFontFam);
  static const IconData chevron_right = const IconData(0xe876, fontFamily: _kFontFam);
  static const IconData funnel = const IconData(0xe88f, fontFamily: _kFontFam);
}